name: Update Custom Domain

on:
  push:
    branches:
      - gh-pages

jobs:
  update-domain:
    runs-on: ubuntu-latest

    steps:
    - name: Check out gh-pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages

    - name: Update custom domain file
      run: echo "www.bradyhawkins.dev" > CNAME

    - name: Commit and push CNAME file
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add CNAME
        git commit -m "Update custom domain to www.bradyhawkins.dev"
        git push origin gh-pages
