name: Update Custom Domain

on:
  push:
    branches:
      - gh-pages

jobs:
  update-domain:
    runs-on: ubuntu-latest

    steps:
    - name: Check out gh-pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages

    - name: Update custom domain file
      run: echo "www.bradyhawkins.dev" > CNAME

    - name: Commit and push CNAME file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add CNAME
        git commit -m "Update custom domain to www.bradyhawkins.dev" || echo "No changes to commit"
        git push origin gh-pages
